Photopix
SC-ECE/WEB-PROJECT pull request #8
Opened 2023-01-02 17:28 UTC by dalalsoham

please accept my pull request.

2023-01-02 17:59 UTC, Priyadarshan2000 approved these changes
@dalalsoham I have resolved your readme.md file conflict. in the next PR careful about this thing. 
LGTM..Great Job 💯 @dalalsoham

2023-01-03 15:40 UTC, swastik-bose007 commented
@dalalsoham There is an responsiveness issue in your website
![image](https://user-images.githubusercontent.com/98341839/210389958-5075f22e-4fea-4736-9aef-570dfcab0e37.png)

check it and try to fix

2023-01-03 18:57 UTC, Priyadarshan2000 requested changes
@dalalsoham in  Single a Pr you can add one project only.  don't add many projects. You delete the chess-game website and upload after this Pr will be merged.

2023-01-03 19:08 UTC, Priyadarshan2000 approved these changes

2023-01-03 19:09 UTC, merged